language: go

go:
- tip # The latest version of Go.

script:
  - go build cli/agenda.go
  - go build service/agenda-service.go
  - go test github.com/weiredsnap/upgraded-agenda/cli/client

branches:
  only:
    - master
